export const GET_VIDEOS_REQUEST = 'GET_VIDEOS_REQUEST';
export const GET_VIDEOS_REQUEST_SUCCESS = 'GET_VIDEOS_REQUEST_SUCCESS';
export const GET_VIDEOS_REQUEST_FAILURE = 'GET_VIDEOS_REQUEST_FAILURE';

export const SAVE_VIDEOS_REQUEST = 'SAVE_VIDEOS_REQUEST';
export const SAVE_VIDEOS_REQUEST_SUCCESS = 'SAVE_VIDEOS_REQUEST_SUCCESS';
export const SAVE_VIDEOS_REQUEST_FAILURE = 'SAVE_VIDEOS_REQUEST_FAILURE';

export const SEARCH_VIDEOS_REQUEST = 'SEARCH_VIDEOS_REQUEST';
export const SEARCH_VIDEOS_REQUEST_SUCCESS = 'SEARCH_VIDEOS_REQUEST_SUCCESS';
export const SEARCH_VIDEOS_REQUEST_FAILURE = 'SEARCH_VIDEOS_REQUEST_FAILURE';
